#! /bin/env python3
# reads json from stdin, and pretty-prints it to stdout with highlighting
# like python3 -m json.tool, but with color
#
# Copyright © 2017 Elad Alfassa <elad@fedoraporject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import sys
from pygments import highlight, lexers, formatters
import collections

RED = "\033[91m"
END= "\033[0m"

# TODO support file input
raw = sys.stdin.read()

try:
    obj = json.loads(raw, object_pairs_hook=collections.OrderedDict)
    jsonstr = json.dumps(obj, sort_keys=False, indent=4)
except json.JSONDecodeError as e:
    print(f"{RED}json decode error.\n{e}{END}\n")
    jsonstr = raw

print(highlight(jsonstr, lexers.JsonLexer(), formatters.TerminalFormatter()))
