#!/bin/bash
# a simple script to set up zram
modprobe zram
echo "Compression streams: "
cat /sys/block/zram0/max_comp_streams
echo "Algorithm: "
cat /sys/block/zram0/comp_algorithm
echo 16G > /sys/block/zram0/disksize
echo "Disk size: 16GB"
mkswap --label zram0 /dev/zram0
swapon --priority 100 /dev/zram0


